Repository knative-extensions/kn-plugin-source-kafka, pull requests merged in 2020-12, with the labels that each got.

#3 Update README to adopt repo change
  README.md
  docs/header.md
  test/e2e-tests.sh
  test/e2e/source_kafka_test.go
Labels: approved, cla: yes, lgtm, size/M

#6 Update OWNERS
  OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#12 Bump strimzi to 0.20.0 and kafka to 2.6.0 for e2e setup
  .github/workflows/knative-style.yaml
  .wokeignore
  test/common.sh
  test/config/100-kafka-ephemeral-triple-2.6.0.yaml
  test/config/100-strimzi-cluster-operator-0.17.0.yaml
  test/config/100-strimzi-cluster-operator-0.20.0.yaml
  test/e2e-tests.sh
  test/local-e2e-tests.sh
Labels: approved, cla: yes, lgtm, size/XXL

#13 Fix release script
  hack/release.sh
Labels: approved, cla: yes, lgtm, size/XS

#14 [main] Fix release script
  hack/release.sh
Labels: approved, cla: yes, lgtm, size/XS

#15 Add CODE_OF_CONDUCT.md and OWNER_ALIASES
  CODE_OF_CONDUCT.md
  OWNERS
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, ok-to-test, size/S
