Repository knative-extensions/kn-plugin-source-kafka, pull requests merged in 2021-12, with the labels that each got.

#135 [main] Update community files
  OWNERS_ALIASES
Labels: cla: yes, approved, lgtm, size/M

#136 [main] Update actions
  .github/workflows/knative-boilerplate.yaml
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-release-notes.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: cla: yes, approved, lgtm, size/M

#137 Add maturity level to readme
  README.md
  docs/header.md
Labels: size/XS, approved, lgtm

#139 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  third_party/VENDOR-LICENSE/knative.dev/networking/pkg/apis/networking/LICENSE
  vendor/knative.dev/serving/pkg/apis/serving/metadata_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/route_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/service_validation.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#138 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, approved, lgtm

#140 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, lgtm, size/M
