Repository knative-extensions/kn-plugin-source-kafka, pull requests merged in 2021-11, with the labels that each got.

#130 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/client/pkg/kn/flags/podspec.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/in_memory_channel_lifecycle.go
  vendor/modules.txt
Labels: cla: yes, approved, lgtm, size/M

#133 Pin Istio tag name
  test/common.sh
Labels: cla: yes, size/XS, approved, lgtm

#131 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/client/pkg/errors/errors.go
  vendor/knative.dev/client/pkg/errors/factory.go
  vendor/knative.dev/client/pkg/kn/config/config.go
  vendor/knative.dev/client/pkg/kn/config/types.go
  vendor/knative.dev/client/pkg/kn/flags/podspec.go
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: cla: yes, approved, size/L, lgtm
