Repository knative-extensions/kn-plugin-source-kafka, pull requests merged in 2021-02, with the labels that each got.

#21 feat: add kafka source list command
  README.md
  go.mod
  go.sum
  pkg/client/client.go
  pkg/client/client_fake.go
  pkg/client/client_test.go
  pkg/factories/boilerplate_test.go
  pkg/factories/command_factory.go
  pkg/factories/command_factory_test.go
  pkg/factories/flags_factory.go
  pkg/factories/flags_factory_test.go
  pkg/factories/rune_factory.go
  pkg/factories/rune_factory_test.go
  pkg/factories/source_factory.go
  pkg/types/interfaces.go
  test/e2e/source_kafka_test.go
  vendor/github.com/maximilien/kn-source-pkg/pkg/commands/source/list.go
  vendor/github.com/maximilien/kn-source-pkg/pkg/core/root.go
  vendor/github.com/maximilien/kn-source-pkg/pkg/factories/command_factory.go
  vendor/github.com/maximilien/kn-source-pkg/pkg/factories/flags_factory.go
  vendor/github.com/maximilien/kn-source-pkg/pkg/factories/rune_factory.go
  vendor/github.com/maximilien/kn-source-pkg/pkg/types/interfaces.go
  vendor/github.com/maximilien/kn-source-pkg/pkg/types/typesfakes/fake_command_factory.go
  vendor/github.com/maximilien/kn-source-pkg/pkg/types/typesfakes/fake_flags_factory.go
  vendor/github.com/maximilien/kn-source-pkg/pkg/types/typesfakes/fake_kn_source_client.go
  vendor/github.com/maximilien/kn-source-pkg/pkg/types/typesfakes/fake_kn_source_factory.go
  vendor/github.com/maximilien/kn-source-pkg/pkg/types/typesfakes/fake_run_efactory.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/XL

#25 Clean up kafkaSource
  pkg/factories/rune_factory.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#26 add CODEOWNERS
  .github/CODEOWNERS
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#27 chore: Add dsimansk to approvers
  OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#28 Prepare dependencies for 0.21.0
  go.mod
  go.sum
  test/e2e-tests.sh
  vendor/knative.dev/client/pkg/kn/commands/types.go
  vendor/knative.dev/client/pkg/serving/v1/client.go
  vendor/knative.dev/client/pkg/serving/v1/client_mock.go
  vendor/knative.dev/client/pkg/serving/v1/gitops.go
  vendor/knative.dev/client/pkg/wait/wait_for_ready.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/metrics/resource_view.go
  vendor/knative.dev/pkg/network/network.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/configuration_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_types.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/route_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/service_validation.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L
