Repository knative-extensions/kn-plugin-source-kafka, pull requests merged in 2021-03, with the labels that each got.

#29 [Automated] Update actions
  .github/workflows/knative-boilerplate.yaml
  .github/workflows/knative-donotsubmit.yaml
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-security.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, cla: yes, lgtm, size/L

#31 [Automated] Fix misspellings
  test/config/100-strimzi-cluster-operator-0.20.0.yaml
Labels: approved, cla: yes, lgtm, size/XS

#32 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/controller/options.go
  vendor/knative.dev/pkg/metrics/exporter.go
  vendor/knative.dev/pkg/metrics/metrics_worker.go
  vendor/knative.dev/pkg/metrics/resource_view.go
  vendor/knative.dev/pkg/network/network.go
  vendor/knative.dev/pkg/system/clock.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#34 Update CODEOWNERS
  .github/CODEOWNERS
Labels: cla: yes, size/XS

#33 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/apis/autoscaling/annotation_validation.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/register.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/v1alpha1/metric_validation.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/v1alpha1/pa_validation.go
  vendor/knative.dev/serving/pkg/apis/config/features.go
  vendor/knative.dev/serving/pkg/apis/serving/metadata_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/register.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/configuration_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/route_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/service_validation.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#35 Update CODEOWNERS
  .github/CODEOWNERS
Labels: approved, cla: yes, lgtm, size/XS

#36 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/controller/controller.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#37 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/controller/controller.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#38 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/client/pkg/dynamic/client.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#39 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing-kafka/pkg/apis/duck/v1alpha1/channelable_combined_types.go
  vendor/knative.dev/eventing-kafka/pkg/apis/duck/v1alpha1/channelable_types.go
  vendor/knative.dev/eventing-kafka/pkg/apis/duck/v1alpha1/subscribable_types.go
  vendor/knative.dev/eventing-kafka/pkg/apis/duck/v1alpha1/subscribable_types_conversion.go
  vendor/knative.dev/eventing-kafka/pkg/apis/duck/v1alpha1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing-kafka/pkg/apis/messaging/v1alpha1/kafka_channel_conversion.go
  vendor/knative.dev/eventing-kafka/pkg/apis/messaging/v1alpha1/kafka_channel_types.go
  vendor/knative.dev/eventing-kafka/pkg/apis/messaging/v1alpha1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/apis/duck/v1alpha1/doc.go
  vendor/knative.dev/eventing/pkg/apis/duck/v1alpha1/register.go
  vendor/knative.dev/eventing/pkg/apis/duck/v1alpha1/resource_types.go
  vendor/knative.dev/eventing/pkg/apis/duck/v1alpha1/zz_generated.deepcopy.go
  vendor/knative.dev/hack/README.md
  vendor/knative.dev/hack/go.sum
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/serving/pkg/apis/serving/register.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#40 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/configs/register.go
  vendor/knative.dev/eventing/pkg/apis/configs/v1alpha1/configmappropagation_defaults.go
  vendor/knative.dev/eventing/pkg/apis/configs/v1alpha1/configmappropagation_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/configs/v1alpha1/configmappropagation_types.go
  vendor/knative.dev/eventing/pkg/apis/configs/v1alpha1/configmappropagation_validation.go
  vendor/knative.dev/eventing/pkg/apis/configs/v1alpha1/doc.go
  vendor/knative.dev/eventing/pkg/apis/configs/v1alpha1/register.go
  vendor/knative.dev/eventing/pkg/apis/configs/v1alpha1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/apis/eventing/register.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/scheme/register.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/XL

#41 [Automated] Update actions
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-release-notes.yaml
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/XS

#42 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/k8s.io/utils/pointer/README.md
  vendor/k8s.io/utils/pointer/pointer.go
  vendor/knative.dev/eventing-kafka/pkg/apis/messaging/v1alpha1/kafka_channel_defaults.go
  vendor/knative.dev/eventing-kafka/pkg/apis/sources/v1beta1/kafka_defaults.go
  vendor/knative.dev/eventing-kafka/pkg/apis/sources/v1beta1/kafka_validation.go
  vendor/knative.dev/hack/README.md
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/microbenchmarks.sh
  vendor/knative.dev/serving/pkg/autoscaler/config/config.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#43 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing-kafka/pkg/apis/sources/v1alpha1/kafka_conversion.go
  vendor/knative.dev/eventing-kafka/pkg/apis/sources/v1alpha1/kafka_types.go
  vendor/knative.dev/eventing-kafka/pkg/apis/sources/v1beta1/kafka_types.go
  vendor/knative.dev/networking/pkg/apis/networking/generic_types.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/ingress_types.go
  vendor/knative.dev/pkg/apis/duck/ABOUT.md
  vendor/knative.dev/pkg/injection/clients.go
  vendor/knative.dev/pkg/injection/interface.go
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/pkg/metrics/exporter.go
  vendor/knative.dev/pkg/test/README.md
  vendor/knative.dev/pkg/test/zipkin/util.go
  vendor/knative.dev/serving/pkg/apis/serving/k8s_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/configuration_types.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_types.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/route_types.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/service_types.go
  vendor/knative.dev/serving/pkg/autoscaler/config/config.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#44 [Automated] Update actions
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/XS

#46 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  third_party/VENDOR-LICENSE/golang.org/x/xerrors/LICENSE
  vendor/github.com/google/go-cmp/cmp/cmpopts/equate.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/errors_go113.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/errors_xerrors.go
  vendor/github.com/google/go-cmp/cmp/report_compare.go
  vendor/github.com/google/go-cmp/cmp/report_slices.go
  vendor/github.com/prometheus/common/model/time.go
  vendor/google.golang.org/grpc/balancer/grpclb/grpc_lb_v1/load_balancer_grpc.pb.go
  vendor/google.golang.org/grpc/credentials/alts/internal/proto/grpc_gcp/handshaker_grpc.pb.go
  vendor/google.golang.org/grpc/encoding/proto/proto.go
  vendor/google.golang.org/grpc/regenerate.sh
  vendor/google.golang.org/grpc/rpc_util.go
  vendor/google.golang.org/grpc/status/status.go
  vendor/google.golang.org/grpc/version.go
  vendor/knative.dev/client/lib/test/revision.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#47 [Automated] Update actions
  .github/workflows/knative-security.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#50 Upgrade to latest dependencies + Update README
  README.md
  go.mod
  go.sum
  vendor/knative.dev/client/pkg/kn/commands/flags/sink.go
  vendor/knative.dev/eventing-kafka/pkg/apis/messaging/v1alpha1/kafka_channel_defaults.go
  vendor/knative.dev/eventing-kafka/pkg/apis/messaging/v1beta1/kafka_channel_defaults.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/trigger_types.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta1/trigger_types.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/subscription_defaults.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/subscription_validation.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1beta1/subscription_defaults.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1beta1/subscription_validation.go
  vendor/knative.dev/hack/e2e-tests.sh
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#49 [Automated] Update actions
  .github/workflows/knative-releasability.yaml
Labels: approved, cla: yes, lgtm, size/XS

#45 Add ce-override option flag for create Kafka source
  README.md
  go.mod
  go.sum
  pkg/client/client.go
  pkg/client/client_test.go
  pkg/factories/command_factory.go
  pkg/factories/flags_factory.go
  pkg/factories/flags_factory_test.go
  pkg/factories/rune_factory.go
  pkg/factories/rune_factory_test.go
  pkg/types/interfaces.go
  pkg/types/structs.go
  test/e2e/source_kafka_test.go
  vendor/knative.dev/client/pkg/dynamic/client.go
  vendor/knative.dev/client/pkg/dynamic/client_mock.go
  vendor/knative.dev/client/pkg/eventing/v1beta1/client.go
  vendor/knative.dev/client/pkg/eventing/v1beta1/client_mock.go
  vendor/knative.dev/client/pkg/kn/commands/flags/sink.go
  vendor/knative.dev/client/pkg/messaging/v1beta1/channels_client.go
  vendor/knative.dev/client/pkg/messaging/v1beta1/channels_client_mock.go
  vendor/knative.dev/client/pkg/messaging/v1beta1/subscriptions_client.go
  vendor/knative.dev/client/pkg/messaging/v1beta1/subscriptions_client_mock.go
  vendor/knative.dev/client/pkg/serving/v1/apply.go
  vendor/knative.dev/client/pkg/serving/v1/client.go
  vendor/knative.dev/client/pkg/serving/v1/client_mock.go
  vendor/knative.dev/client/pkg/serving/v1/gitops.go
  vendor/knative.dev/client/pkg/sources/v1alpha2/apiserver_client.go
  vendor/knative.dev/client/pkg/sources/v1alpha2/apiserver_client_mock.go
  vendor/knative.dev/client/pkg/sources/v1alpha2/binding_client.go
  vendor/knative.dev/client/pkg/sources/v1alpha2/binding_client_mock.go
  vendor/knative.dev/client/pkg/sources/v1alpha2/container_client.go
  vendor/knative.dev/client/pkg/sources/v1alpha2/container_client_mock.go
  vendor/knative.dev/client/pkg/sources/v1alpha2/ping_client.go
  vendor/knative.dev/client/pkg/sources/v1alpha2/ping_client_mock.go
  vendor/knative.dev/client/pkg/wait/poll_watcher.go
  vendor/knative.dev/client/pkg/wait/wait_for_ready.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XL

#48 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/network.go
  vendor/knative.dev/pkg/leaderelection/config.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/M
