Repository knative-extensions/kn-plugin-source-kafka, pull requests merged in 2021-05, with the labels that each got.

#55 [main] Update actions
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-release-notes.yaml
Labels: approved, cla: yes, lgtm, size/S

#56 [main] Update actions
  .github/workflows/knative-boilerplate.yaml
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#57 [Automated] Update knative/community files
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/XS

#58 [main] Update actions
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
Labels: approved, cla: yes, lgtm, size/S

#60 [main] Update actions
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
Labels: approved, cla: yes, lgtm, size/XS

#62 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/client/pkg/eventing/v1/client.go
  vendor/knative.dev/client/pkg/serving/v1/client.go
  vendor/knative.dev/client/pkg/wait/poll_watcher.go
  vendor/knative.dev/client/pkg/wait/wait_for_ready.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#63 [main] Update community files
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/XS

#64 Upgrade Eventing Kafka API to `v1beta1`
  go.mod
  go.sum
  pkg/client/client.go
  pkg/client/client_fake.go
  pkg/client/client_test.go
  pkg/factories/rune_factory.go
  pkg/factories/rune_factory_test.go
  pkg/factories/source_factory.go
  pkg/types/interfaces.go
  pkg/types/structs.go
  vendor/knative.dev/eventing-kafka/pkg/apis/bindings/v1alpha1/doc.go
  vendor/knative.dev/eventing-kafka/pkg/apis/bindings/v1alpha1/kafka_conversion.go
  vendor/knative.dev/eventing-kafka/pkg/apis/bindings/v1alpha1/kafka_defaults.go
  vendor/knative.dev/eventing-kafka/pkg/apis/bindings/v1alpha1/kafka_lifecycle.go
  vendor/knative.dev/eventing-kafka/pkg/apis/bindings/v1alpha1/kafka_types.go
  vendor/knative.dev/eventing-kafka/pkg/apis/bindings/v1alpha1/kafka_validation.go
  vendor/knative.dev/eventing-kafka/pkg/apis/bindings/v1alpha1/register.go
  vendor/knative.dev/eventing-kafka/pkg/apis/bindings/v1alpha1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing-kafka/pkg/apis/sources/v1alpha1/doc.go
  vendor/knative.dev/eventing-kafka/pkg/apis/sources/v1alpha1/kafka_conversion.go
  vendor/knative.dev/eventing-kafka/pkg/apis/sources/v1alpha1/kafka_lifecycle.go
  vendor/knative.dev/eventing-kafka/pkg/apis/sources/v1alpha1/kafka_types.go
  vendor/knative.dev/eventing-kafka/pkg/apis/sources/v1alpha1/kafka_validation.go
  vendor/knative.dev/eventing-kafka/pkg/apis/sources/v1alpha1/register.go
  vendor/knative.dev/eventing-kafka/pkg/apis/sources/v1alpha1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing-kafka/pkg/client/clientset/versioned/scheme/register.go
  vendor/knative.dev/eventing-kafka/pkg/client/clientset/versioned/typed/sources/v1alpha1/doc.go
  vendor/knative.dev/eventing-kafka/pkg/client/clientset/versioned/typed/sources/v1beta1/doc.go
  vendor/knative.dev/eventing-kafka/pkg/client/clientset/versioned/typed/sources/v1beta1/fake/doc.go
  vendor/knative.dev/eventing-kafka/pkg/client/clientset/versioned/typed/sources/v1beta1/fake/fake_kafkasource.go
  vendor/knative.dev/eventing-kafka/pkg/client/clientset/versioned/typed/sources/v1beta1/fake/fake_sources_client.go
  vendor/knative.dev/eventing-kafka/pkg/client/clientset/versioned/typed/sources/v1beta1/generated_expansion.go
  vendor/knative.dev/eventing-kafka/pkg/client/clientset/versioned/typed/sources/v1beta1/kafkasource.go
  vendor/knative.dev/eventing-kafka/pkg/client/clientset/versioned/typed/sources/v1beta1/sources_client.go
  vendor/knative.dev/pkg/apis/duck/v1beta1/destination.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/XXL

#67 [main] Update actions
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/XS

#66 Remove CODEOWNERS
  .github/CODEOWNERS
Labels: approved, cla: yes, lgtm, size/XS

#68 Refactor test setup to auto-resolve released versions
  test/common.sh
  test/e2e-tests.sh
Labels: approved, cla: yes, lgtm, ok-to-test, size/M
