Repository knative-extensions/kn-plugin-source-kafka, pull requests merged in 2021-09, with the labels that each got.

#103 [main] Update actions
  .github/workflows/knative-boilerplate.yaml
  .github/workflows/knative-donotsubmit.yaml
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-security.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: cla: yes, size/S, approved, lgtm

#102 [main] Update community files
  OWNERS_ALIASES
Labels: cla: yes, approved, lgtm, size/M

#104 Fix source target to be Knative Service
  pkg/factories/rune_factory_test.go
Labels: cla: yes, size/XS, approved, lgtm

#105 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: cla: yes, size/XS, approved, lgtm

#106 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/apis/serving/k8s_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_types.go
  vendor/modules.txt
Labels: cla: yes, approved, lgtm, size/M

#108 Remove go-openapi replace from go.mod
  go.mod
  go.sum
  vendor/github.com/go-openapi/spec/.golangci.yml
  vendor/github.com/go-openapi/spec/.travis.yml
  vendor/github.com/go-openapi/spec/README.md
  vendor/github.com/go-openapi/spec/appveyor.yml
  vendor/github.com/go-openapi/spec/bindata.go
  vendor/github.com/go-openapi/spec/cache.go
  vendor/github.com/go-openapi/spec/contact_info.go
  vendor/github.com/go-openapi/spec/errors.go
  vendor/github.com/go-openapi/spec/expander.go
  vendor/github.com/go-openapi/spec/go.mod
  vendor/github.com/go-openapi/spec/go.sum
  vendor/github.com/go-openapi/spec/header.go
  vendor/github.com/go-openapi/spec/items.go
  vendor/github.com/go-openapi/spec/license.go
  vendor/github.com/go-openapi/spec/normalizer.go
  vendor/github.com/go-openapi/spec/operation.go
  vendor/github.com/go-openapi/spec/parameter.go
  vendor/github.com/go-openapi/spec/properties.go
  vendor/github.com/go-openapi/spec/ref.go
  vendor/github.com/go-openapi/spec/resolver.go
  vendor/github.com/go-openapi/spec/response.go
  vendor/github.com/go-openapi/spec/schema.go
  vendor/github.com/go-openapi/spec/schema_loader.go
  vendor/github.com/go-openapi/spec/security_scheme.go
  vendor/github.com/go-openapi/spec/spec.go
  vendor/github.com/go-openapi/spec/validations.go
  vendor/modules.txt
Labels: cla: yes, approved, lgtm, size/XXL

#107 Add support for Darwin/arm64
  hack/release.sh
Labels: cla: yes, size/XS, approved, lgtm

#109 Fix release script for darwin/arm64 bits
  hack/release.sh
Labels: cla: yes, size/XS, approved, lgtm

#110 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/client/pkg/eventing/v1/client.go
  vendor/knative.dev/client/pkg/messaging/v1/channels_client.go
  vendor/knative.dev/client/pkg/messaging/v1/subscriptions_client.go
  vendor/knative.dev/client/pkg/util/unstructured.go
  vendor/knative.dev/serving/pkg/apis/serving/fieldmask.go
  vendor/modules.txt
Labels: cla: yes, approved, lgtm, size/M

#111 [main] Update actions
  .github/workflows/knative-style.yaml
Labels: cla: yes, size/S, approved, lgtm

#112 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/client/pkg/kn/flags/podspec.go
  vendor/knative.dev/client/pkg/kn/flags/podspec_helper.go
  vendor/knative.dev/client/pkg/util/parsing_helper.go
  vendor/modules.txt
Labels: cla: yes, approved, lgtm, size/M

#114 [main] Update community files
  OWNERS_ALIASES
Labels: cla: yes, size/S, approved, lgtm
