Repository knative-extensions/kn-plugin-source-kafka, pull requests merged in 2021-08, with the labels that each got.

#85 [main] Update community files
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#90 Update go version to 1.16
  go.mod
  go.sum
Labels: approved, cla: yes, lgtm, size/XS

#91 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: approved, cla: yes, lgtm, size/XS

#92 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/client/lib/test/broker.go
  vendor/knative.dev/client/pkg/errors/factory.go
  vendor/knative.dev/client/pkg/eventing/v1/client.go
  vendor/knative.dev/client/pkg/kn/plugin/manager.go
  vendor/modules.txt
Labels: cla: yes, approved, size/L, lgtm

#93 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/client/pkg/kn/flags/podspec.go
  vendor/knative.dev/client/pkg/kn/flags/podspec_helper.go
  vendor/knative.dev/eventing-kafka/pkg/apis/messaging/v1beta1/kafka_channel_defaults.go
  vendor/modules.txt
Labels: cla: yes, approved, lgtm, size/M

#94 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/client/pkg/kn/config/config.go
  vendor/knative.dev/client/pkg/kn/config/types.go
  vendor/knative.dev/client/pkg/serving/v1alpha1/client.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/annotation_validation.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/register.go
  vendor/modules.txt
Labels: cla: yes, approved, lgtm, size/M

#95 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: cla: yes, size/XS, approved, lgtm

#96 [main] Update community files
  OWNERS_ALIASES
Labels: cla: yes, size/S, approved, lgtm

#99 [main] Update community files
  OWNERS_ALIASES
Labels: cla: yes, size/S, approved, lgtm

#100 [main] Update actions
  .github/workflows/knative-style.yaml
Labels: cla: yes, size/XS, approved, lgtm
