Repository knative-extensions/kn-plugin-source-kafka, pull requests merged in 2022-10, with the labels that each got.

#244 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#245 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: size/XS, skip-review

#248 fix: build.sh to allow for cross-build
  hack/build.sh
Labels: size/XS, approved, ok-to-test, lgtm

#249 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/apis/serving/fieldmask.go
  vendor/knative.dev/serving/pkg/reconciler/route/config/domain.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#250 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/apis/config/features.go
  vendor/knative.dev/serving/pkg/apis/serving/k8s_validation.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#252 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/knative.dev/pkg/metrics/config_observability.go
  vendor/modules.txt
Labels: approved, lgtm, size/M
