Repository knative-extensions/kn-plugin-source-kafka, pull requests merged in 2022-01, with the labels that each got.

#141 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, approved, lgtm

#146 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/client/pkg/kn/commands/completion_helper.go
  vendor/knative.dev/hack/e2e-tests.sh
  vendor/modules.txt
Labels: approved, lgtm, size/M

#147 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  third_party/VENDOR-LICENSE/k8s.io/klog/LICENSE
  vendor/github.com/go-logr/logr/.golangci.yaml
  vendor/github.com/go-logr/logr/CHANGELOG.md
  vendor/github.com/go-logr/logr/CONTRIBUTING.md
  vendor/github.com/go-logr/logr/README.md
  vendor/github.com/go-logr/logr/discard.go
  vendor/github.com/go-logr/logr/go.mod
  vendor/github.com/go-logr/logr/logr.go
  vendor/k8s.io/klog/.travis.yml
  vendor/k8s.io/klog/CONTRIBUTING.md
  vendor/k8s.io/klog/LICENSE
  vendor/k8s.io/klog/README.md
  vendor/k8s.io/klog/RELEASE.md
  vendor/k8s.io/klog/SECURITY_CONTACTS
  vendor/k8s.io/klog/code-of-conduct.md
  vendor/k8s.io/klog/go.mod
  vendor/k8s.io/klog/go.sum
  vendor/k8s.io/klog/klog.go
  vendor/k8s.io/klog/klog_file.go
  vendor/k8s.io/klog/v2/go.mod
  vendor/k8s.io/klog/v2/go.sum
  vendor/k8s.io/klog/v2/klog.go
  vendor/k8s.io/klog/v2/klog_file.go
  vendor/k8s.io/klog/v2/klog_file_others.go
  vendor/k8s.io/klog/v2/klog_file_windows.go
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/knative.dev/pkg/apis/duck/v1/source_types.go
  vendor/knative.dev/pkg/injection/config.go
  vendor/knative.dev/pkg/test/logging/logging.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL

#148 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/client/pkg/kn/commands/completion_helper.go
  vendor/knative.dev/pkg/leaderelection/config.go
  vendor/knative.dev/pkg/leaderelection/doc.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#142 [main] Update actions
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-security.yaml
  .github/workflows/knative-style.yaml
Labels: size/S, approved, lgtm

#144 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, approved, lgtm

#149 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/apis/serving/k8s_validation.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#150 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/client/pkg/kn/commands/completion_helper.go
  vendor/knative.dev/client/pkg/kn/commands/types.go
  vendor/modules.txt
Labels: approved, size/L, lgtm

#152 Update Strimzi operator in E2E tests
  test/config/100-kafka-ephemeral-triple-3.0.0.yaml
  test/config/100-strimzi-cluster-operator-0.20.0.yaml
  test/config/100-strimzi-cluster-operator-0.27.0.yaml
  test/e2e-tests.sh
Labels: approved, lgtm, size/XXL

#153 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, approved, lgtm

#156 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, approved, lgtm

#158 [main] Update actions
  .github/workflows/knative-security.yaml
Labels: size/XS, approved, lgtm

#155 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, lgtm, size/M

#160 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: size/XS, approved, lgtm

#157 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, approved, lgtm

#162 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/README.md
  vendor/knative.dev/hack/e2e-tests.sh
  vendor/knative.dev/hack/infra-library.sh
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/knative.dev/pkg/resolver/addressable_resolver.go
  vendor/modules.txt
Labels: approved, lgtm, size/M
