Repository knative-extensions/kn-plugin-source-kafka, pull requests merged in 2023-04, with the labels that each got.

#276 [main] Update actions
  .github/workflows/knative-boilerplate.yaml
  .github/workflows/knative-donotsubmit.yaml
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-vulnerability.yaml
Labels: size/L, skip-review

#277 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#278 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#280 Fix Kafka Source setup in E2E tests
  test/common.sh
  test/e2e-tests.sh
Labels: size/S, approved, lgtm

#279 [main] Update actions
  .github/workflows/knative-release-notes.yaml
Labels: size/S, skip-review

#282 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review
