Repository knative-extensions/kn-plugin-source-kafka, pull requests merged in 2025-01, with the labels that each got.

#364 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#366 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: size/S, approved, lgtm

#367 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#365 [release-1.16] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: size/S, approved, lgtm

#369 Update ekb to tagged version
  go.mod
  go.sum
  vendor/modules.txt
Labels: size/XS, approved, lgtm

#371 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#373 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review
